apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-backend
  namespace: {{ .Values.nginx.namespace }}
spec:
  replicas: {{ .Values.nginx.backend.replicaCount }}
  selector:
    matchLabels:
      app: vault-backend
  template:
    metadata:
      labels:
        app: vault-backend
    spec:
      containers:
        - name: vault-backend
          image: {{ .Values.nginx.backend.image }}
          ports:
            - containerPort: {{ .Values.nginx.backend.port }}
          env:
            - name: MASTER_PASSWORD
              value: {{ .Values.nginx.backend.env.MASTER_PASSWORD | quote }}
            - name: DATABASE_URL
              value: {{ .Values.nginx.backend.env.DATABASE_URL | quote }}
          volumeMounts:
{{- if .Values.nginx.backend.volume.enabled }}
            - name: data
              mountPath: {{ .Values.nginx.backend.volume.mountPath }}
{{- end }}
      volumes:
{{- if .Values.nginx.backend.volume.enabled }}
        - name: data
          emptyDir: {}
{{- end }}