apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-frontend
  namespace: {{ .Values.nginx.namespace }}
spec:
  replicas: {{ .Values.nginx.frontend.replicaCount }}
  selector:
    matchLabels:
      app: vault-frontend
  template:
    metadata:
      labels:
        app: vault-frontend
    spec:
      containers:
        - name: vault-frontend
          image: {{ .Values.nginx.frontend.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.nginx.frontend.port }}