apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-ingress
  namespace: {{ .Values.nginx.namespace }}
  annotations:
    {{- range $key, $value := .Values.nginx.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.nginx.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.nginx.ingress.paths.frontend }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.nginx.frontend.name | default "vault-frontend" }}
                port:
                  number: {{ .Values.nginx.frontend.port }}
          - path: {{ .Values.nginx.ingress.paths.backend }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.nginx.backend.name | default "vault-backend" }}
                port:
                  number: {{ .Values.nginx.backend.port }}
  {{- if .Values.nginx.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.nginx.ingress.host | quote }}
      secretName: {{ .Values.nginx.ingress.tls.secretName | quote }}
  {{- end }}